- add MIT license - default to ffmpeg 2.6.2 - download from FFMPEG_RELEASE_URL

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,20 +4,50 @@ indent() {
   sed -u 's/^/       /'
 }
 
-echo "-----> Install ffmpeg"
 BUILD_DIR=$1
-VENDOR_DIR="vendor"
-DOWNLOAD_URL="http://flect.github.io/heroku-binaries/libs/ffmpeg.tar.gz"
+CACHE_DIR=$2
+ENV_DIR=$3
+VENDOR_DIR="$BUILD_DIR/vendor"
+PROFILE_PATH="$BUILD_DIR/.profile.d/ffmpeg.sh"
+FFMPEG_RELEASE_URL="https://ffmpeg.org/releases/ffmpeg-2.6.2.tar.bz2"
 
-echo "DOWNLOAD_URL = " $DOWNLOAD_URL | indent
+if [ -f "$ENV_DIR/FFMPEG_RELEASE_URL" ]; then
+  FFMPEG_RELEASE_URL=$(cat $ENV_DIR/FFMPEG_RELEASE_URL)
+fi
 
-cd $BUILD_DIR
-mkdir -p $VENDOR_DIR
-cd $VENDOR_DIR
-curl -L --silent $DOWNLOAD_URL | tar xz
+FFMPEG_FILE=${FFMPEG_RELEASE_URL##*/}
+
+mkdir="mkdir -p"
+
+tar="tar x"
+case ${FFMPEG_FILE##*.} in
+  bz2) tar=${tar}j ;;
+  gz)  tar=${tar}z ;;
+  *)
+    echo "Fail to uncompress $FFMPEG_FILE because only gzip, bzip2 are supported." | indent
+    exit 1
+    ;;
+esac
+tar="${tar} --checkpoint -C $VENDOR_DIR -f"
+extract=$tar
+
+verify="gpg --verify"
+
+
+echo "-----> Installing ffmpeg..."
+
+$mkdir $VENDOR_DIR
+$mkdir ${PROFILE_PATH%/*}
+
+if [ ! -f "$CACHE_DIR/$FFMPEG_FILE" ]; then
+  curl -L -# --create-dirs -o $CACHE_DIR/$FFMPEG_FILE $FFMPEG_RELEASE_URL
+  curl -L -# --create-dirs -o $CACHE_DIR/$FFMPEG_FILE.asc $FFMPEG_RELEASE_URL.asc
+
+  $verify $CACHE_DIR/$FFMPEG_FILE.asc $CACHE_DIR/$FFMPEG_FILE
+fi
+
+$extract $CACHE_DIR/$FFMPEG_FILE
 
 echo "exporting PATH and LIBRARY_PATH" | indent
-PROFILE_PATH="$BUILD_DIR/.profile.d/ffmpeg.sh"
-mkdir -p $(dirname $PROFILE_PATH)
 echo 'export PATH="$PATH:$HOME/vendor/ffmpeg/bin"' >> $PROFILE_PATH
 echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/vendor/ffmpeg/lib"' >> $PROFILE_PATH
